#!/bin/sh
#
#       /etc/rc.d/init.d/versed
#
#       Daemon for verse server
#
# chkconfig:   2345 20 80
# description: Daemon for verse server

### BEGIN INIT INFO
# Provides:       versed
# Required-Start: $network
# Required-Stop:
# Should-Start:
# Should-Stop:
# Default-Start: 2 3 4 5
# Default-Stop:  0 1 6
# Short-Description: start and stop verse server
# Description: Daemon for verse server
### END INIT INFO

# Source function library.
. /etc/rc.d/init.d/functions

prog="verse_server"
app="/usr/bin/$prog"
lockfile="/var/lock/subsys/$prog"
logfile="/var/log/$prog.log"
confile="/etc/verse/server.ini"
proguser=verse
loglevel="error"

[ -e /etc/sysconfig/$prog ] && . /etc/sysconfig/$prog

start() {
    [ -x $exec ] || exit 5

    echo -n $"Starting $prog: "
    daemon --user $proguser $app -c $confile -D $loglevel -l $logfile -d
    RETVAL=$?
    [ $RETVAL -eq 0 ] && touch $lockfile; success || failure
    echo
    return $RETVAL
}

stop() {
    echo -n $"Stopping $prog: "
    killproc $prog
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f $lockfile
    return $RETVAL
}

restart() {
    stop
    start
}

reload() {
    restart
}

force_reload() {
    restart
}

rh_status() {
    status $prog
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}

case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart)
        $1
        ;;
    reload)
        rh_status_q || exit 7
        $1
        ;;
    force-reload)
        force_reload
        ;;
    status)
        rh_status
        ;;
    condrestart|try-restart)
        rh_status_q || exit 0
        restart
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload}"
        exit 2
esac

exit $?
